language: go
sudo: false
go:
  - 1.4
  - tip
install:
  - go get -t ./...
  - go get golang.org/x/tools/cmd/cover
  - go get github.com/mattn/goveralls
script:
  - go test -v -cover -covermode=count -coverprofile=cover.prof
  - cat cover.prof
  - goveralls -coverprofile cover.prof -repotoken $COVERALLS_TOKEN
